import type { Metadata } from "next";

import "./globals.css";
import Topheader from "./Components/topheader";
import Header from "./Components/header";
import Links from "./Components/links";
import Footer from "./Components/footer";
import { CartProvider } from "../../Context/Cartcontext";






export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased bg-gray-50`}
      >
  
        <div className="min-h-screen flex flex-col">
        
         


          <main className="flex-1 max-w-7xl mx-auto container">
          <Topheader />
            <Header />


          <Links />
          <CartProvider>
           {children}
    

    </CartProvider>
            <Footer />
          </main>

        
        </div>
      </body>
    </html>
  );
}
